Desktop/Sanaullah/sanaapp/config/routes.rb
Rails.application.routes.draw do
  resources :patients
resources :labreports
resources :doctors
resources :treatments

root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/Sanaullah/sanaapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/Sanaullah/sanaapp/app/models/doctor.rb
class Doctor < ApplicationRecord
  #belongs_to :patients
  #belongs_to :labreports
end

Desktop/Sanaullah/sanaapp/app/models/labreport.rb
class Labreport < ApplicationRecord
end

Desktop/Sanaullah/sanaapp/app/models/patient.rb
class Patient < ApplicationRecord
end

Desktop/Sanaullah/sanaapp/app/models/treatment.rb
class Treatment < ApplicationRecord
  #belongs_to :labreports
  #belongs_to :doctors
  #belongs_to :patients
end

Desktop/Sanaullah/sanaapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Desktop/Sanaullah/sanaapp/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	
	def index
		@doctor = Doctor.all
	end
	
	def show
		@doctor = Doctor.find(params[:id])
	end

	def new
	end

	def create
		@doctor = Doctor.new(doctor_params)
		@doctor.save
		redirect_to @doctor
	end

	def edit
		@doctor = Doctor.find(params[:id])
	end
	
	def update
		@doctor = Doctor.find(params[:id])
		if @doctor.update(doctor_params)
			redirect_to @doctor
		else
			render 'edit'
		end
	end
	
	def destroy
		@doctor = Doctor.find(params[:id])
		@doctor.destroy
		redirect_to doctors_path
	end

	private
		def doctor_params
			params.require(:doctor).permit(:dname, :dgender, :dcontact, :ddept, :patient_id, :labreport_id)
		end

end

Desktop/Sanaullah/sanaapp/app/controllers/labreports_controller.rb
class LabreportsController < ApplicationController
	def index
		@labreport = Labreport.all
	end
	def show
		@labreport = Labreport.find(params[:id])
	end

	def new
	end

	def create
		@labreport = Labreport.new(labreport_params)
		@labreport.save
		redirect_to @labreport
	end

	def edit
		@labreport = Labreport.find(params[:id])
	end
	
	def update
		@labreport = Labreport.find(params[:id])
		if @labreport.update(labreport_params)
			redirect_to @labreport
		else
			render 'edit'
		end
	end
	
	def destroy
		@labreport = Labreport.find(params[:id])
		@labreport.destroy
		redirect_to labreports_path
	end

	private
		def labreport_params
		params.require(:labreport).permit(:date, :lreffered, :lreportdate, :lissuedby, :lrmarks)
		end


end

Desktop/Sanaullah/sanaapp/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		@patient = Patient.all
	end
	
	def show
		@patient = Patient.find(params[:id])
	end

	def new
	end

	def create
		@patient = Patient.new(patient_params)
		@patient.save
		redirect_to @patient
	end

	def edit
		@patient = Patient.find(params[:id])
	end
	
	def update
		@patient = Patient.find(params[:id])
		if @patient.update(patient_params)
			redirect_to @patient
		else
			render 'edit'
		end
	end
	
	def destroy
		@patient = Patient.find(params[:id])
		@patient.destroy
		redirect_to patients_path
	end

	private
		def patient_params
		params.require(:patient).permit(:pname, :pgender, :pcontact, :paddress)
		end

end

Desktop/Sanaullah/sanaapp/app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

	def index
		@treatment = Treatment.all
	end
	
	def show
		@treatment = Treatment.find(params[:id])
	end

	def new
	end

	def create
		@treatment = Treatment.new(treatment_params)
		@treatment.save
		redirect_to @treatment
	end

	def edit
		@treatment = Treatment.find(params[:id])
	end
	
	def update
		@treatment = Treatment.find(params[:id])
		if @treatment.update(treatment_params)
			redirect_to @treatment
		else
			render 'edit'
		end
	end
	
	def destroy
		@treatment = Treatment.find(params[:id])
		@treatment.destroy
		redirect_to treatments_path
	end

   private
		def treatment_params
			params.require(:treatment).permit(:medicines, :ttime, :tdate, :nextvisit, :labreport_id, :doctor_id, :patient_id)
		end
end

Desktop/Sanaullah/sanaapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Desktop/Sanaullah/sanaapp/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/Sanaullah/sanaapp/app/helpers/doctors_helper.rb
module DoctorsHelper
end

Desktop/Sanaullah/sanaapp/app/helpers/labreports_helper.rb
module LabreportsHelper
end

Desktop/Sanaullah/sanaapp/app/helpers/patients_helper.rb
module PatientsHelper
end

Desktop/Sanaullah/sanaapp/app/helpers/treatments_helper.rb
module TreatmentsHelper
end

Desktop/Sanaullah/sanaapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Desktop/Sanaullah/sanaapp/app/views/labreports/edit.html.erb
<div class="center jumbotron">
<h1>New Report</h1>

<%= form_for :labreport, url: labreports_path do |l| %>
<p>
<%= l.label :Date %><br>
<%= l.date_select :date, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= l.label :Reffered_By %><br>
<%= l.text_field :lreffered %>
</p>
<p>
<%= l.label :Report_Date %><br>
<%= l.date_select :lreportdate, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= l.label :Issued_By %><br>
<%= l.text_field :lissuedby %>
</p>
<p>
<%= l.label :Report_Details %><br>
<%= l.text_field :lrmarks %>
</p>
<p>
<%= l.submit %>
</p>
<% end %>
<br>
<br>
<a href="/labreports" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/labreports/index.html.erb
<div class="center jumbotron">
<h1>All Lab Reports</h1>
<table border = '1'>
	<tr>
		<th>Test Date</th>
		<th>Reffered By</th>
		<th>Report Date</th>
		<th>Issued By</th>
		<th>Remarks</th>
	</tr>
	<% @labreport.each do |l| %>
		<tr>
			<td><%= l.date %></td>
			<td><%= l.lreffered %></td>
			<td><%= l.lreportdate %></td>
			<td><%= l.lissuedby %></td>
			<td><%= l.lrmarks %></td>
			
			<td><%= link_to 'Show', labreport_path(l) %></td>
			<td><%= link_to 'Edit', edit_labreport_path(l) %></td>
			<td><%= link_to 'Delete', labreport_path(l),
						method: :delete,
						data: { confirm: 'Are you sure to delete?'} %></td>	
		</tr>
	<% end %>
</table>
<br>
<br>
<a href="/labreports/new" class="button buttonb">Make a New Report</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/labreports/new.html.erb
<div class="center jumbotron">
<h1>New Report</h1>

<%= form_for :labreport, url: labreports_path do |l| %>
<p>
<%= l.label :Date %><br>
<%= l.date_select :date, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= l.label :Reffered_By %><br>
<%= l.text_field :lreffered %>
</p>
<p>
<%= l.label :Report_Date %><br>
<%= l.date_select :lreportdate, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= l.label :Issued_By %><br>
<%= l.text_field :lissuedby %>
</p>
<p>
<%= l.label :Report_Details %><br>
<%= l.text_field :lrmarks %>
</p>
<p>
<%= l.submit %>
</p>
<% end %>
<br>
<br>
<a href="/labreports" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/labreports/show.html.erb
<div class="center jumbotron">
<h1>Newly Created Lab Report Details</h1>
<p>
<strong>Date:</strong>
<%= @labreport.date %>
</p>
<p>
<strong>Reffered By:</strong>
<%= @labreport.lreffered %>
</p>
<p>
<strong>Report Date:</strong>
<%= @labreport.lreportdate %>
</p>
<p>
<strong>Report Issued By:</strong>
<%= @labreport.lissuedby %>
</p>
<p>
<strong>Remarks:</strong>
<%= @labreport.lrmarks %>
</p>
<br>
<br>
<a href="/labreports" class="buttonsmall buttonb">Back</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/patients/edit.html.erb
<div class="center jumbotron">
<h1>New Patient</h1>

<%= form_for :patient, url: patients_path do |p| %>
<p>
<%= p.label :Patient_Name %><br>
<%= p.text_field :pname %>
</p>
<p>
<%= p.label :Gender %><br>
<%= p.text_field :pgender%>
</p>
<p>
<%= p.label :Contact %><br>
<%= p.text_field :pcontact %>
</p>
<p>
<%= p.label :Address %><br>
<%= p.text_field :paddress%>
</p>
<p>
<%= p.submit %>
</p>
<% end %>
<br>
<br>
<a href="/patients" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/patients/index.html.erb
<div class="center jumbotron">
<h1>All Patients</h1>
<table border = '1'>
	<tr>
		<th>Name</th>
		<th>Gender</th>
		<th>Contact</th>
		<th>Address</th>
	</tr>
	<% @patient.each do |p| %>
		<tr>
			<td><%= p.pname %></td>
			<td align = "center"><%= p.pgender %></td>
			<td align = "center"><%= p.pcontact %></td>
			<td><%= p.paddress %></td>
			<td><%= link_to 'Show', patient_path(p) %></td>
			<td><%= link_to 'Edit', edit_patient_path(p) %></td>
			<td><%= link_to 'Delete', patient_path(p),
						method: :delete,
						data: { confirm: 'Are you sure you want to delete?'} %></td>
		</tr>
	<% end %>
</table>
<br>
<br>
<a href="/patients/new" class="button buttonb">Register New Patient Here</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/patients/new.html.erb
<div class="center jumbotron">
<h1>New Patient</h1>

<%= form_for :patient, url: patients_path do |p| %>
<p>
<%= p.label :Patient_Name %><br>
<%= p.text_field :pname %>
</p>
<p>
<%= p.label :Gender %><br>
<%= p.text_field :pgender%>
</p>
<p>
<%= p.label :Contact %><br>
<%= p.text_field :pcontact %>
</p>
<p>
<%= p.label :Address %><br>
<%= p.text_field :paddress%>
</p>
<p>
<%= p.submit %>
</p>
<% end %>
<br>
<br>
<a href="/patients" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/patients/show.html.erb
<div class="center jumbotron">
<h1>Newly Created Patient Details</h1>
<p>
<strong>Patient Name:</strong>
<%= @patient.pname %>
</p>
<p>
<strong>Gender:</strong>
<%= @patient.pgender %>
</p>
<p>
<strong>Contact:</strong>
<%= @patient.pcontact %>
</p>
<p>
<strong>Address:</strong>
<%= @patient.paddress %>
</p>
<br>
<br>
<a href="/patients" class="buttonsmall buttonb">Back</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/treatments/edit.html.erb
<div class="center jumbotron">
<h1>New Treatment</h1>

<%= form_for :treatment, url: treatments_path do |t| %>
<p>
<%= t.label :Medicines_Suggested %><br>
<%= t.text_area :medicines %>
</p>
<p>
<%= t.label :Medicines_Suggested_For %><br>
<%= t.text_field :ttime %>
</p>
<p>
<%= t.label :Medicines_Suggested_On %><br>
<%= t.date_select :tdate, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>

<p>
<%= t.label :Next_Visit_On %><br>
<%= t.date_select :nextvisit, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= t.label :Reoprt_ID %><br>
<%= t.text_field :labreport_id %>
</p>
<p>
<%= t.label :Doctor_ID %><br>
<%= t.text_field :doctor_id %>
</p>
<p>
<%= t.label :Patient_ID %><br>
<%= t.text_field :patient_id %>
</p>
<p>
<%= t.submit %>
</p>
<% end %>
<br>
<br>
<a href="/treatments" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/treatments/index.html.erb
<div class="center jumbotron">
<h1>All Treatments</h1>
<table border = '1'>
	<tr>
		<th>Medicines</th>
		<th>To Take For</th>
		<th>Date of Visit</th>
		<th>Next Visit</th>
		<th>Lab Report ID </th>
		<th>Doctor ID </th>
		<th>Patient ID </th>
	</tr>
	<% @treatment.each do |t| %>
		<tr>
			<td><%= t.medicines %></td>
			<td><%= t.ttime %></td>
			<td align = "center"><%= t.tdate %></td>
			<td align = "center"><%= t.nextvisit %></td>
			<td align = "center"><%= t.labreport_id %></td>
			<td align = "center"><%= t.doctor_id %></td>
			<td align = "center"><%= t.patient_id %></td>
			
			<td><%= link_to 'Show', treatment_path(t) %></td>
			<td><%= link_to 'Edit', edit_treatment_path(t) %></td>
			<td><%= link_to 'Delete', treatment_path(t),
						method: :delete,
						data: { confirm: 'Are you sure to delete?'} %></td>	
		</tr>
	<% end %>
</table>
<br>
<br>
<a href="/treatments/new" class="button buttonb">New Treatment</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/treatments/new.html.erb
<div class="center jumbotron">
<h1>New Treatment</h1>

<%= form_for :treatment, url: treatments_path do |t| %>
<p>
<%= t.label :Medicines_Suggested %><br>
<%= t.text_area :medicines %>
</p>
<p>
<%= t.label :Medicines_Suggested_For %><br>
<%= t.text_field :ttime %>
</p>
<p>
<%= t.label :Medicines_Suggested_On %><br>
<%= t.date_select :tdate, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>

<p>
<%= t.label :Next_Visit_On %><br>
<%= t.date_select :nextvisit, {:order => [:day, :month, :year], :prompt => true, :start_year => Time.now.year, :end_year => 2010 } %>
</p>
<p>
<%= t.label :Reoprt_ID %><br>
<%= t.text_field :labreport_id %>
</p>
<p>
<%= t.label :Doctor_ID %><br>
<%= t.text_field :doctor_id %>
</p>
<p>
<%= t.label :Patient_ID %><br>
<%= t.text_field :patient_id %>
</p>
<p>
<%= t.submit %>
</p>
<% end %>
<br>
<br>
<a href="/treatments" class="buttonsmall buttonb">Back</a>
<a href="/" class="buttonsmall buttonb">Home</a>

</div>

Desktop/Sanaullah/sanaapp/app/views/treatments/show.html.erb
<div class="center jumbotron">
<h1>Newly Created Treatment Details</h1>
<p>
<strong>Medicines:</strong>
<%= @treatment.medicines %>
</p>
<p>
<strong>To Take For:</strong>
<%= @treatment.ttime %>
</p>
<p>
<strong>Date:</strong>
<%= @treatment.tdate %>
</p>
<p>
<strong>Next Visit Date:</strong>
<%= @treatment.nextvisit %>
</p>
<p>
<strong>Lab Report ID:</strong>
<%= @treatment.labreport_id %>
</p>
<p>
<strong>Doctor ID:</strong>
<%= @treatment.doctor_id %>
</p>
<p>
<strong>Patient ID:</strong>
<%= @treatment.patient_id %>
</p>
<br>
<br>
<a href="/treatments" class="buttonsmall buttonb">Back</a>
</div>

Desktop/Sanaullah/sanaapp/app/views/welcome/index.html.erb
<div class="center jumbotron">
<h1>Welcome#index</h1>

<a href="/patients" class="buttonsmall buttonb">Patients</a>
<a href="/doctors" class="buttonsmall buttonb">Doctors</a>
<a href="/labreports" class="buttonsmall buttonb">Lab Reports</a>
<a href="/treatments" class="buttonsmall buttonb">Treatments</a>

<p>Find me in app/views/welcome/index.html.erb</p>
</div>